services:
    language-club:
      # build: 
      #   context: react
      image: language-club
      container_name: language-club-app
      working_dir: /src
      # networks: 
      #   - node-network
      # volumes: 
      #   - ./react:/usr/src/app
      #   - /usr/src/app/node_modules
      tty: true
      ports: 
        - "3000:3000"
      command: npm run dev
    db:
        image: postgres
        container_name: db
        restart: always
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=postgres
        tty: true
        volumes:
          - ./data:/var/lib/postgresql/data
        ports: 
          - "5432:5432"